default: &default
  adapter: postgresql
  host: localhost
  user: boummm
  password: thien1998

development:
  <<: *default
  database: hotel_dev

test:
  <<: *default
  database: hotel_test

production:
  <<: *default
